name: Move version to release branch

on:
  push:
    tags:
        - '*'

jobs:
  deploy:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: git merge to release
        run: |
          git config --global user.name 'Team PiCK'
          git config --global user.email 'cyj070513@gmail.com'
          git config pull.rebase false
          git checkout -t origin/release
          echo $(git merge -Xtheirs origin/develop)
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString ${{  github.ref_name }}" Projects/App/Support/Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString ${{  github.ref_name }}" Projects/App/WatchApp/Support/Info.plist
          git add -A
          git commit -m "🚀 :: Deploy version ${{  github.ref_name }}"
          git push
